### ISSUE TITLE
[BUG] detekt config file cleanup and linting errors

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [GangGreenTemperTatum/stickyburp#5]
### Bug Description
Clean build (`./gradlew clean build` from `/`) fails with errors in the `detekt` config file [here](https://github.com/GangGreenTemperTatum/stickyburp/blob/2de74f2f10effc1189b003d7a727b02a17c568ae/config/detekt.yml#L32-L33)

```yml
formatting:
  active: true
  android: false
  autoCorrect: true
```

### Steps to Reproduce
`./gradlew clean build` from `/` (project root)

### Expected Behavior
Task to cleanup/fix the linting errors

### Screenshots
NA

### Environment
NA

### Additional Context
NA

### Console Output
```
Paste any relevant console output here
```
